// <auto-generated />
// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// File is auto-generated by the EF Core tooling.
// To regenerate, run: dotnet ef migrations add <MigrationName>

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using PigeonRacing.Infrastructure.Persistence;

#nullable disable

namespace PigeonRacing.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            // This snapshot is intentionally minimal.
            // Run `dotnet ef migrations add <Name>` to regenerate with full fidelity.
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");
        }
    }
}
